### ISSUE TITLE
Error while opening the terminal

### ISSUE THREAD

**Issue by brunocnunez** [Marqasa/overwatch-crossover-patch#1]
After choosing the Bottle and hit enter, Terminal says:

Overwatch
Downloading dependencies...
Installing dependencies...
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Marqasa** [comment]
I believe this was happening because the Overwatch settings folder was missing. There is a new release which should fix it.
