### ISSUE TITLE
When attempting to enable "DXVK Backend for D3D11", Crossover immediately crashes

### ISSUE THREAD

**Issue by Adamapb** [Marqasa/overwatch-crossover-patch#10]
After successfully applying the patch, toggling the "DXVK Backend for D3D11" option in CrossOver immediately crashes the application.
In the CrossOver error report, a different thread is crashing each time, with the following error message:
```
Thread 8 Crashed::  Dispatch queue: com.apple.root.default-qos
```

I'd be happy to give any more information that you need. Thanks in advance for your help.

**Comment by thinksamwp** [comment]
Which version of CrossOver and macOS are you using?
