### ISSUE TITLE
Crossover Install Location Wrong

### ISSUE THREAD

**Issue by cheesejaguar** [Marqasa/overwatch-crossover-patch#12]
Just installed a fresh copy of Crossover 23.6 on my Mac running Sonoma 14.0, and the script fails with:

```bash
CrossOver not found

Saving session...completed.

[Process completed]

```

The script looks for an install in:
`/Applications/CrossOver.app`

But Crossover installs itself in: 
`/Users/<USER>/Applications/CrossOver.app`

**Comment by cheesejaguar** [comment]
Resolved locally by moving my install, but checking both locations would be nice

**Comment by thinksamwp** [comment]
Good suggestion. I have added a new version (0.4.1) that prompts for a custom location if the default cannot be found.
