### ISSUE TITLE
D3DMetal

### ISSUE THREAD

**Issue by unknownsolo** [Marqasa/overwatch-crossover-patch#13]
Reference to: https://github.com/Marqasa/overwatch-crossover-patch/issues/5

What did you do to get it to work with D3DMetal? I have Sonoma with M3 Max, CrossOver 23.6 and CXPatcher. OW2 only works with DXVK. If I switch to D3DMetal it crashes on boot. 

![Screenshot 2023-11-19 at 11 41 08 AM](https://github.com/Marqasa/overwatch-crossover-patch/assets/86228066/8dd0dbc7-5296-4cac-87ea-5937e3c0842a)

**Comment by thinksamwp** [comment]
Yes, it doesn't work with D3DMetal. There was a trick to revert some of the files back to DXVK but I'm not sure if that still works.
