### ISSUE TITLE
question

### ISSUE THREAD

**Issue by finegorko** [Marqasa/overwatch-crossover-patch#14]
what's difference this patch and CXPatcher? will i need install CXPatcher?

**Comment by thinksamwp** [comment]
This patch updates DXVK, MoltenVK and provides some Overwatch specific improvements such as a shader cache and recommended settings. I can't speak to exactly what CXPatcher does!

**Comment by finegorko** [comment]
> This patch updates DXVK, MoltenVK and provides some Overwatch specific improvements such as a shader cache and recommended settings. I can't speak to exactly what CXPatcher does!

how long to wait dxvk cache? im already waiting 1 hours

**Comment by thinksamwp** [comment]
If you still have the DXVK 'Currently busy' message after 10 or so minutes, I would recommend restarting CrossOver.
