### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by chair-man-f** [Marqasa/overwatch-crossover-patch#16]
change something, relaunch the game, settings revert to ultra

**Comment by thinksamwp** [comment]
I've noticed this happen after a macOS update. It usually sorts itself out after a few restarts.

**Comment by chair-man-f** [comment]
> I've noticed this happen after a macOS update. It usually sorts itself out after a few restarts.

i just delete settings_v0.ini and redo my settings and they save
