### ISSUE TITLE
DXVK Message Not Going Away 

### ISSUE THREAD

**Issue by Segadude23** [Marqasa/overwatch-crossover-patch#17]
I've tried reinstalling the game on Steam and the game does run, but the message never goes away. All it does it disappear for a slight millisecond and start blinking in and out. I've tried waiting over 10 minutes and restarting crossover but it's always there even after waiting a good while (20-30 minutes). Should I install it without a client and make it's own bottle or try to install the game though the battle.net client?

**Comment by thinksamwp** [comment]
The blinking in and out is normal. The message should go away after 5-10 minutes. Sometimes I get the issue where it doesn't go away but it is usually resolved by restarting CrossOver. Beyond that it's possible reinstalling the patch might help but I can't say for sure.
