### ISSUE TITLE
Failed to copy file error

### ISSUE THREAD

**Issue by omikun** [Marqasa/overwatch-crossover-patch#19]
Running latest patch on crossover 23.7.1 in Sonoma 14.1.1

bash-3.2$ sudo ./overwatch-crossover-patch-2
Password:
Enter your Overwatch bottle name (or path with --path /path/to/bottle):
--path /Users/sli/CXPBottles/Steam/
✔ Please select your game client: · Steam
Downloading dependencies...
Installing dependencies...
Failed to copy file: /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/wine/dxvk/d3d10_1.dll
Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }

**Comment by thinksamwp** [comment]
You may need to give Terminal Full Disk Access. You can do this by going to System Settings > Privacy & Security > Full Disk Access and adding Terminal to the list.

**Comment by omikun** [comment]
Thanks that fixed my issue!
