### ISSUE TITLE
Cannot download Overwatch in crossover

### ISSUE THREAD

**Issue by ForeverAT** [Marqasa/overwatch-crossover-patch#20]
It cannot download in crossover, but it open the battlenet app and download in it.
I check and found overwatch under the c-drive of the battle net, not under it's own bottle
Will this affect the running of the patch code?

**Comment by thinksamwp** [comment]
It should run fine, if there is an issue the patch let you know what the error is.

**Comment by ForeverAT** [comment]
Thanks, I fixed it with the guide.
For user who face this, you may choose Battle.net Desktop App as your bottle and turn on the DZVK for that bottle.
