### ISSUE TITLE
Unable to get bottle path to recognize installation on Mac OS Sonoma

### ISSUE THREAD

**Issue by jcrandallijm** [Marqasa/overwatch-crossover-patch#21]
I have tried to point it directly to the .exe, to the file containing the exe (_retail_), and to the main overwatch file (Overwatch). It doesn't recognize the file path. Any help would be appreciated. 
<img width="577" alt="SCR-20240208-jobf" src="https://github.com/Marqasa/overwatch-crossover-patch/assets/96733065/5d6ede86-74cd-4411-bbe9-dc9df7721d83">

**Comment by thinksamwp** [comment]
If you are using the default CrossOver bottle location, you can simply enter the bottle name, for example, "Battle.net Desktop app."

The --path option is for bottles installed in alternative locations, like an external SSD. In such cases, provide the full path up to the bottle name. In your example you would need to remove "/drive_c/Program Files (x86)/Overwatch/_retail_/Overwatch.exe" from the path.
