### ISSUE TITLE
Never prompted at step 9

### ISSUE THREAD

**Issue by Thegman34** [Marqasa/overwatch-crossover-patch#24]
Hi,

 I followed all the steps and ran the command line. I'm running fresh installs of crossover and OW2. 

After completing step #8, I never received a prompt. Any ideas?

Thanks.

**Comment by thinksamwp** [comment]
You should see the prompt, "Enter your Overwatch bottle name (or path with --path /path/to/bottle):" in the terminal after running the patch.

**Comment by reppy-c** [comment]
Hi,

Is there an example of what the path should be?  I've googled and checked various reddit posts but am not able to actually find where the Crossover bottle path is, I've found a few different Crossover directories but no specific Overwatch bottle file or directory to point the patch to. I've tried copying the patcher to various directories and running it but no luck.

I've installed everything in the default directories. Even if someone is able to post their example, it would help me find where to point it on my machine.

Thanks in advance

**Comment by thinksamwp** [comment]
Glad you figured it out!
