### ISSUE TITLE
mouse lag in overwatch

### ISSUE THREAD

**Issue by Timmyz03** [Marqasa/overwatch-crossover-patch#25]
mac book pro 16inch M1 Pro on Sonoma 

I have mouse acceleration turned off and the mouse works perfectly in its cursor form, aka on screen clicking things, selecting hero etc. (I've tried this with multiple mouse and the issue persists) 

However, when in the first person mode (when actually playing fps), looking around cause pseudo mouse acceleration where the mouse seems to not capture some sensor data and be randomly slower (as if the desk suddenly got very sticky and hard to push through). Can be tested by putting the mouse against some books, moving it out and back against the book. normally the crosshair should return to the same spot, however it sometimes go further or less than expected, not returning to the original position (more prominent with big movements and high polling rate)

I am not sure if this is a overwatch/patch/crossover/Mac issue, but it has been bothering me for a long time and was wondering if there is a fix.

**Comment by thinksamwp** [comment]
This would fall outside the scope of this repo and is probably a Mac/Crossover/Wine issue. Hard to say for sure what would be causing it!
