### ISSUE TITLE
broken and cant login too

### ISSUE THREAD

**Issue by sawawas** [Marqasa/overwatch-crossover-patch#3]
yes i wait for dxvk loading in the bottom left

also my battle.net app is very glitchy after doing this like the update and play button has a seizure but i cannot disable and re enable it and overwatch needs a patch everytime i go to open it if that matters
<img width="343" alt="Screen Shot 2023-05-01 at 12 53 34 pm" src="https://user-images.githubusercontent.com/57820278/235398696-51dcc55e-3ebb-4ef8-bab5-06e653598fa1.png">

opening from the battle.net launcher logs me in but everything looks like this and logs me out after a few minutes of very slowly loading menu items
<img width="2240" alt="Screen Shot 2023-05-01 at 11 54 24 am" src="https://user-images.githubusercontent.com/57820278/235392619-a79b8582-9b9d-4b84-be36-9330ff6ad80a.png">
ok now i notice its saying dxvk is busy again... maybe it was because i relaunch trying to get in logged in, do i have wait for dxvk every time i play even though after i cant login? anyway things have loaded but then it logs me out after waiting??? (it froze here and disconnected)
<img width="2240" alt="Screen Shot 2023-05-01 at 11 54 42 am" src="https://user-images.githubusercontent.com/57820278/235392633-8ea6fd3f-7892-4052-b354-ee56b57cfa43.png">
yea just after it gives connection lost screen, dxvk is burning my computer again and taking forever and login isnt working
<img width="2240" alt="Screen Shot 2023-05-01 at 12 06 03 pm" src="https://user-images.githubusercontent.com/57820278/235393700-b037c6fd-e189-41b5-a65d-a65bd0c1ec21.png">
(this screenshot is from after this attempt because i forgot to screenshot)
it finished quicker but login still forever shows connecting (did i mention that? dont even know if im getting my password wrong but im pretty sure not trying 3 times)
<img width="2240" alt="Screen Shot 2023-05-01 at 12 01 54 pm" src="https://user-images.githubusercontent.com/57820278/235393369-71caf5ca-1237-48ad-a685-271dbd84430c.png">

i press cancel then exit to desktop once the login screen shows again, relaunching repeats this with letting me in and doing stupid dxvk and i cant login 
<img width="2240" alt="Screen Shot 2023-05-01 at 12 05 26 pm" src="https://user-images.githubusercontent.com/57820278/235393666-362bd18a-d84c-454c-9959-e2afbefebd61.png">
clicking stuff also no work 

sorry my english and brain is stupid i didnt sleep much recently too i tried to make it as clear as possible, logging in connecting takes 30 seconds on my switch and the first time i waited when again dxvk was finished it took 20 minutes before stopping but i cant be bothered to wait so long it obviously dont work after 5 
<img width="2240" alt="Screen Shot 2023-05-01 at 12 32 04 pm" src="https://user-images.githubusercontent.com/57820278/235395711-de3ddb6f-7d70-410a-95c9-d09087e0b375.png">

**Comment by sawawas** [comment]
i got in but buttons are missing like game select and nothing loads in settings, i can still play but this is stupid
<img width="2240" alt="Screen Shot 2023-05-01 at 12 37 11 pm" src="https://user-images.githubusercontent.com/57820278/235396081-4348da03-dab6-444a-9d3b-749e24aa4a22.png">
<img width="2240" alt="Screen Shot 2023-05-01 at 12 37 19 pm" src="https://user-images.githubusercontent.com/57820278/235396095-3f57703a-9f36-4005-bebe-95e9b91f1bb8.png">
ok logged out again :/ , funny how the change hero keybind is missing but it flashes "H" when i kill something

**Comment by thinksamwp** [comment]
The game runs slowly when you first launch it while DXVK compiles shaders. I suggest waiting on the login screen for a few minutes before logging in.

**Comment by thinksamwp** [comment]
The missing menu elements are listing in the known issues. Nothing we can do about this at the moment unfortunately!

**Comment by Tile124** [comment]
Having the same issue, i've been waiting about half an hour and opening it multiple times
