### ISSUE TITLE
How to build from source code?

### ISSUE THREAD

**Issue by balmic** [Marqasa/overwatch-crossover-patch#4]
Hi there,

Wondering what is required to build this from source? I have the game installed on an external drive/settings in unusual places, and believe that could be the reason why I'm getting an Os error. Can you please assist.

Downloading dependencies...
Installing dependencies...
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

Thanks!

**Comment by thinksamwp** [comment]
I have released a new version which should contain some more useful error messages. Also, you are welcome to download the source code and modify it if you like!
