### ISSUE TITLE
Have you tried MetalD3D?

### ISSUE THREAD

**Issue by zaptrem** [Marqasa/overwatch-crossover-patch#5]
Performance and compatibility across many games has been better with GPTK/MD3D-patched Crossover. Have you found any success?

**Comment by thinksamwp** [comment]
Yes, Overwatch is running quite well with CXPatcher + GPTK on Sonoma (I wasn't able to get it running on Ventura). All menu elements are now visible, including kill feed and match chat. The mouse unlock issue is still present unfortunately. Performance is about the same, although Sonoma does crash somewhat frequently so be wary of that!

**Comment by unknownsolo** [comment]
What did you do to get it to work with D3DMetal? I have Sonoma with M3 Max, CrossOver 23.6 and CXPatcher. OW2 only works with DXVK. If I switch to D3DMetal it crashes on boot. 

![Screenshot 2023-11-19 at 11 41 08 AM](https://github.com/Marqasa/overwatch-crossover-patch/assets/86228066/8dd0dbc7-5296-4cac-87ea-5937e3c0842a)
