### ISSUE TITLE
lag in game after update

### ISSUE THREAD

**Issue by sawawas** [Marqasa/overwatch-crossover-patch#6]
ive been playing overwatch through crossover using this tutorial https://www.youtube.com/watch?v=AxKK3ctISnk after the recent game update it's giving me 10 fps in game no matter what :(

i know i should update the patch but im not sure how to go about it and dont want to mess it up, my bandwidth is very limited i cant just reinstall everything

**Comment by sawawas** [comment]
ok i just redid the steps and it seems ok, infact running way better than before… i dont think i had esync on last time, should i keep it on?

**Comment by thinksamwp** [comment]
Yes, I would leave ESync enabled.
