### ISSUE TITLE
Shader loading

### ISSUE THREAD

**Issue by MarynaPetrova** [Marqasa/overwatch-crossover-patch#7]
When I first launched the game, shader loading took 1-2 minutes. People told me and videos also mentioned that the loading would take 6-10 minutes. Is it normal that I had a very fast shader loading?

**Comment by thinksamwp** [comment]
It usually takes about 5 or 6 minutes for me. 1-2 minutes does seem quite fast!

**Comment by MarynaPetrova** [comment]
Thank you for the response, I was starting to worry :)
One more question, will shader downloading time occur every time I enter the game?

**Comment by sawawas** [comment]
everyone says it does but i have problems and played alot so it eventually went away, i don’t know if that’s even possible but for you just wait 30 seconds and queue then it should be done

**Comment by thinksamwp** [comment]
The shaders do need to compile every time you launch the game, yes.
