### ISSUE TITLE
CrossOver 23

### ISSUE THREAD

**Issue by MarynaPetrova** [Marqasa/overwatch-crossover-patch#8]
Will the patch work under version 23 of CroosOver?

**Comment by vinhtq115** [comment]
> Will the patch work under version 23 of CroosOver?

OW2 works on CrossOver 23 without patching. UI elements show correctly. Graphic glitches and initial delay still occur though.

**Comment by thinksamwp** [comment]
Yes, it should work fine :)

**Comment by MarynaPetrova** [comment]
I tried it and...
Unfortunately, the fps dropped to 70 and there were a lot of visual glitches.

**Comment by thinksamwp** [comment]
From my testing on macOS Sonoma, base CrossOver 23 runs as you described but with the patch it is running as well as CrossOver 22! Mouse detach issue still remains though.

**Comment by MarynaPetrova** [comment]
But your patch is not compatible with the 23rd version of the crossover, I've already tried patching 23. Nevertheless, your patch is still really awesome :)

**Comment by thinksamwp** [comment]
Did you get an "Operation not permitted" error? If so you may need to give Full Disk Access to the Terminal. You can do this by going to System Settings > Privacy & Security > Full Disk Access and adding Terminal to the list.

**Comment by MarynaPetrova** [comment]
https://github.com/Marqasa/overwatch-crossover-patch/assets/128310719/f611da1a-3767-4836-9e4b-6d5da9b98c8d
"Pay no attention to the watermark (I was trying to reduce the video's size)."

**Comment by MarynaPetrova** [comment]
I don't have this error, but there was another one, I don't remember which one.
WOWWWW, and now the terminal says that the installation is successful.
Even though I didn't change anything (the terminal already had access to the disk).     🥳

**Comment by MarynaPetrova** [comment]
Is there a way to temporarily disable the patch?

**Comment by thinksamwp** [comment]
You could rename the patched version and keep it installed alongside an unpatched version. Then just open the one you want. Your bottles will be the same for both.

**Comment by sawawas** [comment]
> I tried it and...
> Unfortunately, the fps dropped to 70 and there were a lot of visual glitches. :(

70? i have my graphics on lowest and can only hit 70 with crossover 22… no visual glitches ofc but im curious if you’ve done something

**Comment by MarynaPetrova** [comment]
I have DXVK, Esync, and graphics on medium.

**Comment by sawawas** [comment]
hmm ok playing boarderless cuts my frames in half
